[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_BASE_URL = "http://4.213.224.142:3000"

[[redirects]]
  from = "/api/*"
  to = "http://4.213.224.142:3000/api/:splat"
  status = 200
  force = true

# Removed the catch-all redirect as it conflicts with Next.js routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

[[plugins]]
  package = "@netlify/plugin-nextjs" 