ALTER TABLE signal_history_analytics
ADD COLUMN IF NOT EXISTS status VARCHAR CHECK (status IN ('RUNNING', 'SUCCESS', 'STOP_LOSS', 'CANCELLED')) DEFAULT 'RUNNING',
ADD COLUMN IF NOT EXISTS direction VARCHAR CHECK (direction IN ('LONG', 'SHORT')) DEFAULT 'SHORT',
ADD COLUMN IF NOT EXISTS entry_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp_low NUMERIC,
ADD COLUMN IF NOT EXISTS tp_high NUMERIC,
ADD COLUMN IF NOT EXISTS stop_price NUMERIC,
ADD COLUMN IF NOT EXISTS opened_at DATE,
ADD COLUMN IF NOT EXISTS closed_at DATE,
ADD COLUMN IF NOT EXISTS exit_price NUMERIC,
ADD COLUMN IF NOT EXISTS exit_reason VARCHAR,
ADD COLUMN IF NOT EXISTS confidence NUMERIC,
ADD COLUMN IF NOT EXISTS quantity NUMERIC,
ADD COLUMN IF NOT EXISTS extras VARCHAR;


-- ALTER TABLE signal_history_analytics
-- ADD COLUMN IF NOT EXISTS extras VARCHAR;
-- DROP COLUMN IF EXISTS extras;